# Generated by Django 3.2.13 on 2024-07-26 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(default=None, max_length=100, null=True)),
                ('companyname', models.CharField(default=None, max_length=100, null=True)),
                ('address', models.CharField(default=None, max_length=200, null=True)),
                ('pincode', models.CharField(default=None, max_length=20, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(default=None, max_length=30, null=True)),
                ('fblink', models.URLField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('jobdesc', models.CharField(default=None, max_length=700, null=True)),
                ('basicpay', models.CharField(default=None, max_length=50, null=True)),
                ('salary_currency', models.CharField(default=None, max_length=3, null=True)),
                ('salary_type', models.CharField(default='monthly', max_length=50, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('postdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('jobtype', models.CharField(default='full_time', max_length=50)),
                ('eid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.employer')),
            ],
        ),
    ]
